### ISSUE TITLE
Remove xcvbnm, make this the default

### ISSUE THREAD

**Issue by enyo** [careapp-inc/zxcvbn-dart#5]
Hi,

I'm the maintainer of `xcvbnm` and just realised what you wrote in your README: our implementation of the algorithm returns incorrect results.

I'll be switching to your version, but I think it would be better to change your API to fit better with dart.

Instead of creating the `Zxcbnm` class with only one function, I think it makes much more sense to convert this to a top level function:

This:

```dart
import 'package:zxcvbn/zxcvbn.dart';
void main() {
  final zxcvbn = Zxcvbn();
  final result = zxcvbn.evaluate('P@ssw0rd');
}
```

then becomes this:

```dart
import 'package:zxcvbn/zxcvbn.dart' as zxcvbn;
void main() {
  final result = zxcvbn.evaluate('P@ssw0rd');
}
```

In any way, I'll be adding a note to our README that your library should be used instead.

**Comment by MichaelMarner** [comment]
Hi @enyo 

I meant no disrespect with what's in our readme. In hindsight after doing this port I'm fairly certain the issues with xcvbnm on Flutter come down to numeric precision errors (if Dart is transpiled to Javascript all number types become floats), as I saw lots of integer overflow errors in making this port. I initially tried to find out where the differences between Real Zxcvbn and Xcvbnm came from, but without being able to compare the code directly it was really difficult. In the end we decided on a Dart port that is very close to the CoffeeScript was the easiest way forward.

I agree, I don't think this needs to be wrapped in a class, as it's just a single Function. Personally I like using classes because it makes things easier to mock in tests (eg widget shows correct info based on Mock Zxcvbn calculation), but wrapping this function would give the same functionality.

**Comment by enyo** [comment]
Hi @MichaelMarner ,
No worries, I didn't feel disrespected in any way :)
I understand your point about using objects. I guess it's a general shortcoming of dart, that they recommended (namespaced) top level functions without the ability to actually mock them in tests...
